### ISSUE TITLE
How up to date?

### ISSUE THREAD

**Issue by sparcut** [teijo/iba-cocktails#5]
Hey,

Sweet set you've made.

Are you keeping it up to date?

Cheers.

**Comment by teijo** [comment]
Thanks,

I don't think the list actually changes as it's the list of the classic cocktails listed at IBA's website http://iba-world.com/. The data might not be 100% comprehensive though when it comes to e.g. taste profiles, which can be subjective too, I guess.

If you spot that something is missing, let me know.
